github: rix4uni
liberapay: rix4uni
patreon: rix4uni
ko_fi: rix4uni
open_collective: rix4uni
bitcoin: ADDRESS
ethereum: ADDRESS | NAME
buy_me_a_coffee: rix4uni
community_bridge: linkinspector
issuehunt: rix4uni
polar: rix4uni
thanks_dev: rix4uni
custom: https://www.paypal.me/rix4uni